.TH PO-DIFF 1 "Februari 2026" "po-diff 1.0.0" "Användarkommandon"
.SH NAMN
po-diff \- jämför PO/TS-översättningsfiler
.SH SYNOPSIS
.B po-diff
[\fIFLAGGOR\fR] \fIGAMMAL_FIL\fR \fINY_FIL\fR
.SH BESKRIVNING
.B po-diff
jämför två gettext .po eller Qt .ts-filer och visar skillnaderna.
.SH FLAGGOR
.TP
.BR \-f ", " \-\-format " " \fIFORMAT\fR
Utdataformat: text (standard), json, html
.TP
.BR \-o ", " \-\-output " " \fIFIL\fR
Spara rapport till fil
.TP
.BR \-h ", " \-\-help
Visa hjälp
.TP
.BR \-v ", " \-\-version
Visa version
.SH FÖRFATTARE
Daniel Nylander <daniel@danielnylander.se>
